/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Intoduction;
/**
 * @author anass 
 */
import java.awt.Color;
import  java.sql.Connection;
import java.sql.DriverManager;
import  java.sql.Statement;
import  java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;



public class AssoMawada extends javax.swing.JFrame {

    /** Creates new form Form Asso Mawadda */
    public AssoMawada() {
        initComponents();
    }
    
   
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtNbreFils = new javax.swing.JTextField();
        txtdateNaiss = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStg = new javax.swing.JTable();
        btnPremier = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnRecherhcer = new javax.swing.JButton();
        btnAfficher = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtRecherhcer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NiveauScolaire = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        SituationFamil = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        Profession = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        situationHome = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        Maladie = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtfilsMalade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnbreFilsEcolier = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNbrePrimaire = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtmoyenne4 = new javax.swing.JTextField();
        txtmoyenne5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        NiveauScolaire1 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        SituationFamil1 = new javax.swing.JComboBox();
        txtmoyenne6 = new javax.swing.JTextField();
        txtnomfemme = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        Profession1 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtmoyenne8 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtmoyenne9 = new javax.swing.JTextField();
        txtnbreDiplome = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBoxState = new javax.swing.JComboBox();
        jRadioButton6 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("جمعية المودة للتنمية و الأعمال الاجتماعية");
        setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("الرقم");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("إسم المستفيد");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("مكان ازدياد");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("عدد الأولاد");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("تاريخ ازدياد ");

        TableStg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Ttitle5", "Title6"
            }
        ));
        TableStg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStg);

        btnPremier.setText("<<");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnSuivant.setText(">");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnPrecedent.setText("<");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        btnDernier.setText(">>");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnRecherhcer.setText("Rechercher");
        btnRecherhcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherhcerActionPerformed(evt);
            }
        });

        btnAfficher.setText("Afficher");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("رقم");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(" دوي اعاقة او مرض مزمن");

        jLabel6.setText("Recherhcer par :");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Intoduction/arp.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("العنوان");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("الهاتف");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("المستوى الدراسي");

        NiveauScolaire.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "كتاب قرآني", "ابتدائي", "اعدادي", "جامعي", "ثانوي" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("الحالة العائلية");

        SituationFamil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عازب", "متزوج", "مطلق", "ارمل" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("المهنة");

        Profession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عامل", "مستخدم", "مياوم", "حرفي حر", "تقني", "موضف", "اطار", "عاطل" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("الوضعية السكنية");

        situationHome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مالك", "مكتري", "سكن مع الاب او الام" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("الحالة الصحية للأب");

        Maladie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مرض مزمن", "اعاقة", "عادية" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText(" دوي اعاقة او مرض مزمن");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("عدد المتمدرسين");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("عدد  المتمدرسين الابتدائي");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("الحاصلين على شواهد");

        jLabel19.setText(" ذكور");

        jLabel20.setText("إناث");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("إسم الزوجة");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("تاريخ ازدياد ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("المستوى الدراسي");

        NiveauScolaire1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "كتاب قرآني", "ابتدائي", "اعدادي", "جامعي", "ثانوي" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("الحالة العائلية");

        SituationFamil1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عازب", "متزوج", "مطلق", "ارملة", "عاملة" }));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("الحالة الصحية ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مرض مزمن", "اعاقة", "عادية" }));

        Profession1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عاملة", "مستخدمة", "مياومة", "حرفية حرة", "تقنية", "موضفة", "اطار", "عاطلة", "ربة بيت" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("المهنة");

        jButton1.setText("Aide");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aideClique(evt);
            }
        });

        jLabel27.setText(" ذكور");

        jLabel28.setText("إناث");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("الحاصلين على شواهد");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("مكتري");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText(" المتمدرسين الابتدائي");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("الجهة");

        jComboBoxState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "اولاد مالك", "الضرابنة" }));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("ارملة");

        jMenu1.setText("Pour signaler une erreur ou demander une information, merci d'envoyer un email : rach@th3pf.com");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(476, 476, 476)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRecherhcer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnRecherhcer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jRadioButton6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtmoyenne9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmoyenne8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNbrePrimaire, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtmoyenne4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmoyenne5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtnbreDiplome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnomfemme, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmoyenne6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SituationFamil1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NiveauScolaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Profession1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNbreFils)
                            .addComponent(txtfilsMalade)
                            .addComponent(txtnbreFilsEcolier, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel15)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Profession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(situationHome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SituationFamil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NiveauScolaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Maladie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14))
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addGap(11, 11, 11)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtdateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDernier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel9))))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(NiveauScolaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtNbrePrimaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(txtmoyenne8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmoyenne9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(SituationFamil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(txtmoyenne5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmoyenne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnbreDiplome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel21)
                                .addComponent(txtnomfemme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(situationHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmoyenne6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Maladie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NiveauScolaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SituationFamil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Profession1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNbreFils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtfilsMalade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(txtnbreFilsEcolier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPremier, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPrecedent)
                                    .addComponent(btnSuivant)
                                    .addComponent(btnDernier))))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(txtRecherhcer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRecherhcer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)))
                .addGap(69, 69, 69)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//          Load Form AssoMawadda
    
    
    
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try{
        // connexion avec base de donnée tsdi.
        Class.forName("com.mysql.jdbc.Driver");
        String ArabeUnicode= "?useUnicode=yes&characterEncoding=UTF-8";
        cnx = DriverManager.getConnection("jdbc:mysql://localhost/association"+ArabeUnicode,"root","");
        St = cnx.createStatement();
        
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        
      

        dt = new DefaultTableModel();
        dt.addColumn("الرقم");
        dt.addColumn("إسم المستفيد");
        dt.addColumn("مكان ازدياد");
        dt.addColumn("عدد الأولاد");
        dt.addColumn("تاريخ ازدياد ");
        dt.addColumn("العنوان");
        dt.addColumn(" الهاتف");
        dt.addColumn("المستوى الدراسي");
        dt.addColumn("الحالة العائلية");
        dt.addColumn(" المهنة");
        dt.addColumn("الجهة");
        TableStg.setModel(dt);
        // afficehr la liste des personnes الهاتف الحالة العائلية
        AfficherPersonne();
        // remplir les champs 
        i = 0;
        DeplacerStagiaire(i);
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n"+e.getMessage());
    }
}//GEN-LAST:event_formWindowOpened

//          PREMIER
private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
    try{
        i = 0;
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnPremierActionPerformed
//          PRECEDENT
private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
    try{
        i--;
        DeplacerStagiaire(i);
        // ou DeplacerStagiaire(--i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnPrecedentActionPerformed
//          SUIVANT
private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
    try{
        i++;
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnSuivantActionPerformed
//          DERNIER
private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
    try{
        i = dt.getRowCount() - 1 ;
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnDernierActionPerformed
//          selectionnéé stg
private void TableStgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStgMouseClicked
    try{
        i = TableStg.getSelectedRow();
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
    }
}//GEN-LAST:event_TableStgMouseClicked
 
//          Ajouter 
private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
    try{
        
        String Adr = txtAdresse.getText();
        String Tel = txtTelephone.getText();
        String Niv = (String)NiveauScolaire.getSelectedItem();
        String SitF = (String)SituationFamil.getSelectedItem();
        String Prof = (String)Profession.getSelectedItem();
        // non affiché sur l'appli dispo sur la bdd :
        String SitH = (String)situationHome.getSelectedItem();
        String Mala = (String)Maladie.getSelectedItem();
        String nbreF = txtNbreFils.getText();
        String filsM = txtfilsMalade.getText();
        String filsE = txtnbreFilsEcolier.getText();
        String EcolP = txtNbrePrimaire.getText();
        String state = (String) jComboBoxState.getSelectedItem();
        String nbDip = txtnbreDiplome.getText();
        String nomFe = txtnomfemme.getText();
        
        // verifier si deja exist
        boolean b = false;
        for(int j=0; j < dt.getRowCount() ;j++){
            if(Integer.parseInt(txtmat.getText()) == dt.getValueAt(j, 0)){
                b = true;
                break;
            }
        }
        if(b == false){
           
            St.executeUpdate("Insert into stg Values("+txtmat.getText()+",'"+txtnom.getText()+"','"+txtprenom.getText()+"',"+txtNbreFils.getText()+",'"+txtdateNaiss.getText()+"','"+Adr+"','"+Tel+"','"+Niv+"','"+SitF+"','"+Prof+"','"+SitH+"','"+Mala+"','"+nbreF+"','"+filsM+"','"+filsE+"','"+EcolP+"','"+state+"','"+nbDip+"','"+nomFe+"')");
            AfficherPersonne(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "La personné a été ajouté avec succés");
        }else{
            JOptionPane.showMessageDialog(null, "matricule déja existe !");
            txtmat.setText("");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout \n"+e.getMessage());
    }
}//GEN-LAST:event_btnAjouterActionPerformed
//          MODIFIER 
private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
    try{ // simple quote pour nom prenom dateNaiss
        // msg d confirmation !
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            St.executeUpdate("UPDATE stg SET nom='"+txtnom.getText()+"',prenom='"+txtprenom.getText()+"',NbreEnfants="+txtNbreFils.getText()+",dateNaiss='"+txtdateNaiss.getText()+"'  WHERE mat = "+ txtmat.getText());                                
            AfficherPersonne(); // recharger la liste des Personnes
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }
}//GEN-LAST:event_btnModifierActionPerformed
//          supprimer 
private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
    try{
        if(JOptionPane.showConfirmDialog(null, "Confirmer la suppression","Supprimer la personne",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            if(txtmat.getText().length() != 0){
                St.executeUpdate("Delete from stg where mat = "+ txtmat.getText());
                AfficherPersonne(); // recharger la liste des Personnes ...
            }else{
                JOptionPane.showMessageDialog(null, "veuillez remplir champ matricule !");
            }
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer stg !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnSupprimerActionPerformed
//          afficher 
private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
    try{
        AfficherPersonne();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur btn afficher !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnAfficherActionPerformed
//          rechercher 
private void btnRecherhcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherhcerActionPerformed
    try{
        dt.setRowCount(0); // vider la liste des personnes
        if(jRadioButton1.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("Select * From stg WHERE mat = "+txtRecherhcer.getText());
        }
         if(jRadioButton3.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Nombre fils diplomés` != 0");
        }
          if(jRadioButton4.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Situation Maison` = 'مكتري'");
        }
           if(jRadioButton5.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Nombre ecoliers primaire` != 0 ");
        }
            if(jRadioButton6.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Situation Familiale` = 'ارمل' ");
        }
             if(jRadioButton6.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Situation Familiale` ='ارملة' ");
        }
          
        else{
            Rs = St.executeQuery("SELECT * FROM `stg` WHERE `Nombre Fils Malade` != 0");
        }
        while(Rs.next()){
            mat = Rs.getInt("mat"); // la même chose
            nom = Rs.getString(2);
            prenom = Rs.getString(3);
            NbreEnfants = Rs.getInt(4);
            dateNaiss = Rs.getDate(5);
            Object[] stg = {mat,nom,prenom,NbreEnfants,dateNaiss,adresse,telephone, niveauScolaire,situationFamil,profe,states};
            dt.addRow(stg);
        }
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucune Personne");
            AfficherPersonne(); // afficehr tout les personnes
        }else{
            i = 0;
            DeplacerStagiaire(i);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur btn rechercher  !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnRecherhcerActionPerformed

    private void txtmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatActionPerformed

    private void aideClique(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aideClique
       JOptionPane.showMessageDialog(null, "Pour toute demande d'information veuiller contacter :  \n Anass RACH \n Email : anas.rach@gmail.com ou rach@th3pf.com \n Site web : www.anasrach.com");
        
    }//GEN-LAST:event_aideClique

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed
//          procedure qui rempli les champs ...
private void DeplacerStagiaire(int i){
    try{
        if (dt.getRowCount() == 0){
            btnPrecedent.setEnabled(false);
            btnSuivant.setEnabled(false);
            txtmat.setText("");
            txtnom.setText("");
            txtprenom.setText("");
            txtNbreFils.setText("");
            txtdateNaiss.setText("");
            txtAdresse.setText("");
            txtTelephone.setText("");
        }else{
            if(i == 0){
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(true);
            }else if (i == dt.getRowCount()-1){ // dernier enregistrement
                btnPrecedent.setEnabled(true);
            btnSuivant.setEnabled(false);
            }else{
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(true);
            }
            if(dt.getRowCount() == 1){
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(false);
            }
        }
        txtmat.setText(dt.getValueAt(i, 0).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        txtnom.setText(dt.getValueAt(i, 1).toString());
        txtprenom.setText(dt.getValueAt(i, 2).toString());
        txtNbreFils.setText(dt.getValueAt(i, 3).toString());
        txtdateNaiss.setText(dt.getValueAt(i, 4).toString());
        txtAdresse.setText(dt.getValueAt(i, 5).toString());
        txtTelephone.setText(dt.getValueAt(i, 6).toString());
    }catch(Exception e){
        // JOptionPane.showMessageDialog(null, "Erreur deplacement\n"+e.getMessage());
    }
}
//          procedure qui Afficher la liste des personnes.
private void AfficherPersonne(){
    try{
        dt.setRowCount(0); // vider la list des persoonnes
        Rs = St.executeQuery("Select * From stg");
        
        while(Rs.next()){
            mat = Rs.getInt("mat");
            nom = Rs.getString("nom");
            prenom = Rs.getString("prenom");
            NbreEnfants = Rs.getInt("NbreEnfants");
            dateNaiss = Rs.getDate("dateNaiss");
            adresse = Rs.getString("Adresse");
            telephone= Rs.getString("Telephone");
            niveauScolaire = Rs.getString("NiveauScolaire");
            situationFamil = Rs.getString("Situation Familiale");
            profe = Rs.getString("Profession");
            states = Rs.getString("State");
            
            Object[] stg = {mat,nom,prenom,NbreEnfants,dateNaiss,adresse,telephone, niveauScolaire,situationFamil,profe,states};
            dt.addRow(stg);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur afficher la liste des Personnes\n"+e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssoMawada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssoMawada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssoMawada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssoMawada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AssoMawada().setVisible(true);
            }
        });
    }
    
    // Déclaration des variables.
    private Connection cnx;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int mat;
    private String nom ,prenom,adresse,telephone, niveauScolaire, situationFamil, profe, states;
    private int NbreEnfants;
    private Date dateNaiss;    
  
    private int i; // indice de déplacement
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Maladie;
    private javax.swing.JComboBox NiveauScolaire;
    private javax.swing.JComboBox NiveauScolaire1;
    private javax.swing.JComboBox Profession;
    private javax.swing.JComboBox Profession1;
    private javax.swing.JComboBox SituationFamil;
    private javax.swing.JComboBox SituationFamil1;
    private javax.swing.JTable TableStg;
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnRecherhcer;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBoxState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox situationHome;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtNbreFils;
    private javax.swing.JTextField txtNbrePrimaire;
    private javax.swing.JTextField txtRecherhcer;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtdateNaiss;
    private javax.swing.JTextField txtfilsMalade;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtmoyenne4;
    private javax.swing.JTextField txtmoyenne5;
    private javax.swing.JTextField txtmoyenne6;
    private javax.swing.JTextField txtmoyenne8;
    private javax.swing.JTextField txtmoyenne9;
    private javax.swing.JTextField txtnbreDiplome;
    private javax.swing.JTextField txtnbreFilsEcolier;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomfemme;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
//              PROGRAMME réalisé par : Rach Anass